name: Test

on:
  push:
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  integration:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - php_version: '8.2'
            wp_version: '6.2'
            multisite: false
          - php_version: '8.2'
            wp_version: '6.3'
            multisite: false
          - php_version: '8.2'
            wp_version: '6.4'
            multisite: false
          - php_version: '8.2'
            wp_version: 'latest'
            multisite: false
          - php_version: '8.2'
            wp_version: '6.2'
            multisite: true
          - php_version: '8.2'
            wp_version: '6.3'
            multisite: true
          - php_version: '8.2'
            wp_version: '6.4'
            multisite: true
          - php_version: '8.2'
            wp_version: 'latest'
            multisite: true

    name: "Integration Test: PHP ${{ matrix.php_version }} | WP ${{ matrix.wp_version }}${{ matrix.multisite == true && ' (+ ms)' || '' }}"

    continue-on-error: ${{ matrix.wp_version == 'trunk' }}

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root # Change this to your desired MySQL root password
          MYSQL_DATABASE: wordpress_tests
          MYSQL_USER: root
          MYSQL_PASSWORD: root # Change this to your desired MySQL root password
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=10s --health-retries=10

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php_version }}
          ini-values: zend.assertions=1, error_reporting=-1, display_errors=On
          coverage: none

      - name: "Composer: remove the PHP platform requirement"
        run: composer config --unset platform.php

      - name: "Install Composer dependencies"
        uses: ramsey/composer-install@v2
        with:
          dependency-versions: "highest"
          composer-options: "yoast/wp-test-utils --with-dependencies"
          custom-cache-suffix: $(date -u -d "-0 month -$(($(date +%d)-1)) days" "+%F")

      - name: Change permissions for install-wp-tests.sh
        run: chmod +x tests/bin/install-wp-tests.sh

      - name: Install WP
        shell: bash
        run: tests/bin/install-wp-tests.sh wordpress_tests root '' 127.0.0.1:3306 ${{ matrix.wp_version }}

      - name: Run unit tests - single site
        run: composer test

      - name: Run unit tests - multisite
        if: ${{ matrix.multisite == true }}
        run: composer test
        env:
          WP_MULTISITE: 1
